name: React App Deployment # Workflow name

on:
  push:
    branches:
      - main # Branch to trigger the deployment

jobs:
  deploy-react-to-gh-pages:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # Cache dependencies
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install dependencies
        run: npm ci  # Faster and safer than `npm i`

      # Build the React app
      - name: Build
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.TOKENS}}  # Fixed secret name
          publish_dir: ./dist  # Ensure Vite's `base` is set correctly in vite.config.ts
