name: Build & Deploy of the practice app

on:
  push:
    branches:
      - main

env:
  CI: false

jobs:  
  build:
    name: Build
    runs-on: ubuntu-latest

    outputs:
      artifact_name: ${{ steps.upload.outputs.artifact_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: List build directory contents
        run: ls -la ./build

      - name: Upload production-ready build files
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: production-files-${{ github.run_id }}  # Dynamic name
          path: ./build
          include-hidden-files: true

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - Print artifact name
        run: echo "Artifact name: ${{ needs.build.outputs.artifact_name }}"

      - name: Download artifact
        uses: actions/download-artifact@v4  
        with:
          name: ${{ needs.build.outputs.artifact_name }}  # Use dynamic name
          path: ./build

      - name: Verify downloaded files
        run: ls -la ./build  

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build
